const Content = () => {
  return (
    <div className="rich-text-section">
      <p>
        Stroke.so (<strong>“Stroke”, “we”, “us”, and “our”</strong>) is a
        desktop application designed to help you create and edit content, such
        as text and images, using an AI co-creator. Our Privacy Policy (“Privacy
        Policy”) covers the personal information we collect about you when you
        use our application, or otherwise interact with us, including through
        our website at stroke.so, and our related online and offline offerings
        (collectively, the <strong>“Service”</strong>).
      </p>
      <p>
        This Privacy Policy does not apply to any third-party websites,
        services, or applications, even if they are accessible through our
        Service. In addition, a separate privacy notice, which is available upon
        request if it applies to you, governs personal information we receive
        from our current or prospective employees and contractors.
      </p>
      <p>
        If you are using the Service as an employee, contractor, or other
        representative of an organization (e.g., your employer) and you have any
        questions about our privacy practices or would like to exercise any
        rights with respect to your personal information, please contact your
        organization, as they may be responsible for managing your data.
      </p>
      <p>
        By using our Service, you agree to be bound by this Privacy Policy. If
        you don’t agree to this Privacy Policy, do not use the Service. If you
        access and use the Service on behalf of a company (such as your
        employer) or other legal entity, you represent and warrant that you have
        the authority to bind that company or other legal entity to this Privacy
        Policy. In that case, “you” and “your” will refer to that company or
        other legal entity.
      </p>
      <section className="rich-text-section" id="information">
        <h2 className="title-s mt-8">1. Personal information we collect</h2>
        <p>
          We collect personal information when you provide it to us, when you
          use our Service, and when other sources provide it to us, as further
          described below.
        </p>
        <p>
          <strong>A. Information You Provide to Us</strong>
        </p>
        <p>
          <strong>Account Creation. </strong>When you create an account, we
          collect information such as your name, email address, password, and an
          optional profile photo.
        </p>
        <p>
          <strong>Your Communications with us. </strong>We collect personal
          information from you such as email address, phone number, or mailing
          address when you request information about our Service, register for
          our newsletter, request customer or technical support, or otherwise
          communicate with us. We also collect the contents of messages or
          attachments that you may send to us, as well as other information you
          choose to provide, and that may be associated with your
          communications.
        </p>
        <p>
          <strong>Payment Information.</strong>We may sell services through our
          Services. When you make purchases through the Services, we may use a
          third-party application to process your payments. These third-party
          applications may collect certain financial information from you to
          process a payment on behalf of Raizer, including your name, email
          address, mailing address, payment card information, and other billing
          information. Raizer does not store or receive your payment
          information, but it may store and receive information associated with
          your payment information (e.g., your billing details).
        </p>
        <p>
          <strong>Surveys. </strong>We may contact you to participate in
          surveys, especially as part of the beta testing of Stroke.so. If you
          decide to participate, you may be asked to provide certain
          information, which may include personal information.
        </p>
        <p>
          <strong>Use of the Services. </strong>We collect information you
          provide to the Service for the purpose of providing the Service to
          you, which may include personal information. This includes text,
          images, or other materials you create, edit, or upload (&quot;User
          Content&quot;), as well as content generated by the AI co-creator
          (&quot;Generated Content&quot;).
        </p>
        <p>
          <strong>Customer Service, Training and Quality Assurance. </strong>
          If you call or otherwise interact with Stroke’s sales, customer
          service, or support personnel, we may collect the information you
          provide to our representatives. In addition, we may record telephone
          calls or video conferences between you and our representatives for
          training or quality assurance purposes.
        </p>
        <p>
          <strong>B. Information Collected Automatically</strong>
        </p>
        <p>
          <strong>Automatic Data Collection. </strong>We may collect certain
          information automatically when you use the Service. This information
          may include your Internet protocol (IP) address, user settings,
          details about your operating system or device, location information
          (inferred based on your IP address), Internet service provider, and
          information about how you interact with and use the Service. In some
          instances, a User ID may be generated to track usage counts and
          product performance for development purposes during beta testing.
        </p>
        <p>
          <strong>Analytics. </strong>We may use third-party service providers
          to collect and process analytics and other information about our
          Service. These third-party service providers may collect and store
          analytics and other information about your usage of the Service. They
          have their own privacy policies addressing how they use the analytics
          and other information, and we do not have access to, nor control over,
          third parties’ use of analytics data.
        </p>
        <p>
          <strong>Cookies (Website Only). </strong>
          On our website (e.g., stroke.so), we may use cookies and similar
          technologies to collect information about your interactions, such as
          pages visited and links clicked. Cookies are small text files placed
          in device browsers to store preferences. Most browsers allow you to
          block and delete cookies, but if you do so, some features of the
          website may not work properly. For more information, see Section 6
          (&quot;Your Choices&quot;).
        </p>
        <p>
          <strong>C. Information from Other Sources</strong>
        </p>
        <p>
          <strong>Third Party Services and Organizations. </strong>We may obtain
          information about you from other sources, including through
          third-party services and organizations. For example, if you use
          third-party integrations (such as Google Drive or Dropbox) with our
          Service, we may collect information about you from that third party
          that you have made available via your privacy settings.
        </p>
        <p>
          <strong>D. Information We Do Not Collect</strong>
        </p>
        <p>
          We do not intentionally collect sensitive or special category personal
          information, such as genetic data, biometric data for the purposes of
          uniquely identifying a natural person, health information, or
          religious information.
        </p>
        <p>
          We do not knowingly collect information from or direct any of our
          Service or content specifically to children under the age of 13. If we
          learn or have reason to suspect that a user is under the age of 13, we
          will close that account.
        </p>
      </section>
      <section className="rich-text-section" id="lawful-basis">
        <h2 className="title-s mt-8">
          {" "}
          2. Lawful Basis and Purposes for Processing Your Personal Information
        </h2>
        <p>
          If you are an individual in the United Kingdom or European Economic
          Area (EEA), we collect and process information about you only where we
          have legal bases for doing so under applicable United Kingdom and/or
          EU laws. The legal bases depend on the Service you use and how you use
          it. This means we collect and use your information only where:
        </p>
        <p>
          <strong>
            To Fulfill a Contract or Take Steps Linked to a Contract with You:
          </strong>
        </p>
        <ul>
          <li>Administer access to your accounts;</li>
          <li>
            Provide our Service, including generating content using the AI
            co-creator;
          </li>
          <li>Send you service-related communications;</li>
          <li>Provide you with customer support.</li>
        </ul>
        <p>
          <strong>Legitimate Interests:</strong>
        </p>
        <ul>
          <li>Improve and personalize your experience with our Service;</li>
          <li>
            Understand how you use our Service to develop new features,
            functionality, and services, especially during beta testing;
          </li>
          <li>
            Monitor and improve the performance of our Service for
            administrative, security, and fraud prevention purposes;
          </li>
          <li>Conduct internal research and analytics;</li>
          <li>Enforce compliance with our Terms of Use and other policies;</li>
          <li>Respond to your requests, questions, and feedback;</li>
          <li>
            Comply with applicable laws, lawful requests, and legal processes,
            such as responding to subpoenas or requests from government
            authorities.
          </li>
        </ul>
        <p>
          <strong>Consent:</strong>
        </p>
        <ul>
          <li>
            Where you have expressly indicated your consent to the processing of
            your personal information (e.g., to receive marketing
            communications);
          </li>
          <li>
            On other occasions where we ask for your consent, for the purpose we
            explain at the time.
          </li>
        </ul>
        <p>
          You may withdraw your consent at any time by contacting us using the
          details in Section 10 (&quot;Contact Us&quot;).
        </p>
      </section>
      <section className="rich-text-section" id="use-information">
        <h2 className="title-s mt-8"> 3. How we use your information</h2>
        <p>
          We use your personal information for a variety of business purposes,
          including to:
        </p>
        <p>
          <strong>
            Provide the Services or Requested Information, such as:
          </strong>
        </p>
        <ul>
          <li>Fulfilling our contract with you;</li>
          <li>Identifying and communicating with you;</li>
          <li>Managing your information and account;</li>
          <li>
            Processing your payments and otherwise servicing your purchase
            orders;
          </li>
          <li>Responding to questions, comments, and other requests;</li>
          <li>
            Providing access to certain areas, functionalities, and features of
            our Services;
          </li>
          <li>
            Generating content using the AI co-creator based on your inputs;
          </li>
          <li>Answering requests for customer or technical support.</li>
        </ul>
        <p>
          <strong>
            Serve Administrative and Communication Purposes, such as:
          </strong>
        </p>
        <ul>
          <li>
            Pursuing legitimate interests, such as research and development
            (including improving the AI co-creator), network and information
            security, and fraud prevention;
          </li>
          <li>
            Measuring interest and engagement in our Service, including
            analyzing your usage of the Service during beta testing;
          </li>
          <li>Developing new features and improving the Service;</li>
          <li>Ensuring internal quality control and safety;</li>
          <li>Authenticating and verifying individual identities;</li>
          <li>Carrying out audits;</li>
          <li>
            Communicating with you about your account, activities on our
            Services and Privacy Policy changes;
          </li>
          <li>
            Preventing and prosecuting potentially prohibited or illegal
            activities;
          </li>
          <li>Enforcing our agreements;</li>
          <li>Complying with our legal obligations;</li>
        </ul>
        <p>
          <strong>Use of User Content and Generated Content: </strong>
        </p>

        <ul>
          <li>
            We use your User Content to provide the Service, including
            generating Generated Content via the AI co-creator.
          </li>
          <li>
            Unless you enable Privacy Mode (as described in our Terms of Use),
            we may use your User Content and Generated Content to improve and
            enhance the Service, including for training AI models, and for other
            development, diagnostic, and corrective purposes in connection with
            the Service and other Happy Vibes, Inc. offerings. If Privacy Mode
            is enabled, your User Content is used only to generate Generated
            Content in real-time and is deleted afterward, and it is not used
            for training AI models.
          </li>
        </ul>
        <p>
          <strong>De-identified and Aggregated Information Use:</strong>We may
          use personal information and other data about you to create
          de-identified and/or aggregated information. De-identified and/or
          aggregated information is not personal information, and we may use and
          disclose such information in a number of ways, including research,
          internal analysis, analytics, and any other legally permissible
          purposes, such as publishing reports on trends in the usage of our
          Service.
        </p>
        <p>
          <strong>Cross-Device Tracking: </strong>Your activity may be tracked
          across different devices. For example, we may attempt to match your
          activity on one device with your activity on another device to improve
          the Service and provide a consistent experience.
        </p>
        <p>
          <strong>How We Use Automatic Collection Technologies: </strong>Our
          uses of Technologies fall into the following general categories:
        </p>
        <ul>
          <li>Operationally Necessary;</li>
          <li>Performance Related;</li>
          <li>Functionality Related;</li>
          <li>Advertising or Targeting Related.</li>
        </ul>
        <p>
          Please note that this Privacy Policy covers only our use of
          Technologies and does not govern the use of Technologies by any third
          parties.
        </p>
      </section>
      <section className="rich-text-section" id="third-parties">
        <h2 className="title-s mt-8">
          4. Disclosing your information to third parties
        </h2>
        <p>
          We may share your personal information with the following categories
          of third parties:
        </p>
        <p>
          <strong>Service Providers. </strong>We may share any personal
          information we collect about you with our third-party service
          providers. The categories of service providers to whom we entrust
          personal information include service providers for: (i) the provision
          of the Service; (ii) the provision of information, products, and other
          services you have requested; (iii) customer service activities; and
          (iv) the provision of IT and related services, including third-party
          AI models used for the AI co-creator functionality. Examples of such
          providers include:
        </p>
        <ul>
          <li>Cloud hosting providers;</li>
          <li>Analytics providers;</li>
          <li>Collaboration tools.</li>
        </ul>
        <p>
          <strong>Affiliates. </strong>We may share personal information with
          our affiliated entities.
        </p>
        <p>
          <strong>Third-Party Integrations. </strong>If you use third-party
          integrations (such as Google Drive or Dropbox) with our Service, we
          may share your information with those third parties as necessary to
          provide the integration. These third parties have their own privacy
          policies, and we are not responsible for their privacy practices.
        </p>
        <p>
          <strong>Your Organization. </strong>If you access the Services on
          behalf of an organization, we may share your information with that
          organization at its request. Please note that your information may
          also be subject to your organization’s privacy policy. We are not
          responsible for the privacy or security practices of our customers.
        </p>
        <p>
          <strong>Disclosures to Protect Us or Others. </strong>We may access,
          preserve, and disclose any information we store in association with
          you to external parties if we, in good faith, believe doing so is
          required or appropriate to: (i) comply with law enforcement or
          national security requests and legal process, such as a court order or
          subpoena; (ii) protect your, our, or others’ rights, property, or
          safety; (iii) enforce our policies or contracts; (iv) collect amounts
          owed to us; or (v) assist with an investigation and prosecution of
          suspected or actual illegal activity.
        </p>
        <p>
          <strong>
            Disclosure in the Event of Merger, Sale, or Other Asset Transfer.{" "}
          </strong>
          If we are involved in a merger, acquisition, financing due diligence,
          reorganization, bankruptcy, receivership, purchase or sale of assets,
          or transition of service to another provider, then your information
          may be sold or transferred as part of such a transaction, as permitted
          by law and/or contract.
        </p>
      </section>
      <section className="rich-text-section" id="transfer-information">
        <h2 className="title-s mt-8">
          5. Cross-Border Transfer of Personal Information
        </h2>
        <p>
          The Service is hosted in the United States, and the personal
          information we collect will be stored and processed on our servers in
          the United States. Our employees, contractors, and affiliated
          organizations that process information for us may be located in the
          United States or in other countries outside of your home country,
          which may have different data protection standards than those in your
          home country.
        </p>
        <p>
          Where your personal information is transferred outside of the EEA,
          Switzerland, or the UK, and where this is to a country not subject to
          an adequacy decision by the EU Commission or considered adequate as
          determined by applicable data protection laws, we will take steps to
          ensure your personal information is adequately protected by safeguards
          such as Standard Contractual Clauses (SCCs) approved by the EU
          Commission or the UK Government. A copy of the relevant mechanism can
          be obtained for your review on request by using the contact details in
          Section 10 (&quot;Contact Us&quot;).
        </p>
      </section>
      <section className="rich-text-section" id="your-choices">
        <h2 className="title-s mt-8">6. Your Choices</h2>
        <p>
          <strong>General. </strong>You may have the right to opt out of certain
          uses of your personal information.
        </p>
        <p>
          <strong>Email Communications.</strong>We may send you certain
          non-promotional communications regarding us and our Service, and you
          will not be able to opt out of those communications (e.g.,
          communications regarding the Service or updates to this Privacy
          Policy).
        </p>
        <p>
          <strong>Privacy Mode.</strong>You may enable Privacy Mode in the
          Service settings to prevent your User Content from being used to train
          AI models. When Privacy Mode is enabled, your User Content is used
          only to generate Generated Content in real-time and is deleted
          afterward.
        </p>
        <p>
          <strong>Cookies. </strong>You may stop or restrict the placement of
          Technologies on your device or remove them by adjusting your
          preferences as your browser or device permits. The online advertising
          industry also provides websites from which you may opt out of
          receiving targeted ads from data partners and other advertising
          partners that participate in self-regulatory programs. You can access
          these websites and learn more about targeted advertising and consumer
          choice and privacy, at{" "}
          <a href="https://www.networkadvertising.org/">
            www.networkadvertising.org
          </a>
          ,{" "}
          <a href="https://www.youronlinechoices.eu/">
            www.youronlinechoices.eu
          </a>
          ,{" "}
          <a href="https://youradchoices.ca/choices/">
            www.youradchoices.ca/choices
          </a>
          , and{" "}
          <a href="https://www.aboutads.info/choices/">
            www.aboutads.info/choices/
          </a>
          .
        </p>
        <p>
          Please note you must separately opt out in each browser and on each
          device.
        </p>
        <p>
          <strong>“Do Not Track”. </strong>Do Not Track (<strong>“DNT”</strong>)
          is a privacy preference that users can set in certain web browsers.
          Please note that we do not respond to DNT signals or similar
          mechanisms transmitted by web browsers.
        </p>
      </section>
      <section className="rich-text-section" id="privacy-rights">
        <h2 className="title-s mt-8">7. Your Privacy Rights</h2>
        <p>In accordance with applicable laws, you may have the right to:</p>
        <ul>
          <li>
            <strong>Access </strong>personal information about you consistent
            with legal requirements;
          </li>
          <li>
            <strong>Request Correction </strong>of your personal information
            where it is inaccurate or incomplete;
          </li>
          <li>
            <strong>Request Deletion </strong>of your personal information,
            subject to certain exceptions prescribed by law;
          </li>
          <li>
            <strong>Request Restriction </strong>of our processing of your
            personal information;
          </li>
          <li>
            <strong>Withdraw your Consent </strong>to our processing of your
            personal information;
          </li>
        </ul>
        <p>
          These rights may be limited, for example, if fulfilling your request
          would reveal personal information about another person, or if you ask
          us to delete information that we are required by law or have
          compelling legitimate interests to keep.
        </p>
        <p>
          If you would like to exercise any of these rights, please contact us
          as set forth below. We will process such requests in accordance with
          applicable laws. To protect your privacy, we will take steps to verify
          your identity before fulfilling your request.
        </p>
      </section>
      <section className="rich-text-section" id="data-retention">
        <h2 className="title-s mt-8">8. Data Retention and Deleteion</h2>
        <p>
          We store the personal information we receive as described in this
          Privacy Policy for as long as your account is active or as necessary
          to fulfill the purpose(s) for which it was collected, provide our
          Service, resolve disputes, establish legal defenses, conduct audits,
          pursue legitimate business purposes, enforce our agreements, and/or
          comply with applicable laws.
        </p>
        <p>
          Retention periods will be determined taking into account the type of
          information collected and the purpose for which it is collected,
          bearing in mind the requirements applicable to the situation and the
          need to destroy outdated, unused information at the earliest
          reasonable opportunity. For example:
        </p>
        <ul>
          <li>
            Data related to your account will be retained as long as your
            account is active.
          </li>
          <li>
            User Content and Generated Content may be retained longer if used
            for training AI models (unless Privacy Mode is enabled).
          </li>
        </ul>
        <p>
          If you already have an account on the Service, you may access, update,
          alter, or delete your basic user profile information by logging into
          your account and updating your profile settings. For more information
          on our retention periods, you can contact us using the details in
          Section 10 (&quot;Contact Us&quot;).
        </p>
      </section>
      <section className="rich-text-section" id="other-conditions">
        <h2 className="title-s mt-8">9. Other Conditions</h2>
        <p>
          <strong>International Data Transfers.</strong> All information
          processed by us may be transferred, processed, and stored anywhere in
          the world, including but not limited to the United States or other
          countries, which may have data protection laws that are different from
          the laws where you live. We endeavor to safeguard your information
          consistent with the requirements of applicable laws.
        </p>
        <p>
          <strong>Security of your information.</strong> We take steps to ensure
          that your information is treated securely and in accordance with this
          Privacy Policy. Unfortunately, no system is 100% secure, and we cannot
          ensure or warrant the security of any information you provide to us.
          To the fullest extent permitted by applicable laws, we do not accept
          liability for unauthorized disclosure.
        </p>
        <p>
          By using the Service or providing personal information to us, you
          agree that we may communicate with you electronically regarding
          security, privacy, and administrative issues relating to your use of
          the Service. If we learn of a security system’s breach, we may attempt
          to notify you electronically by posting a notice on the Service, by
          mail, or by sending an email to you.
        </p>
        <p>
          You are responsible for selecting any password and its overall
          security strength, ensuring the security of your own information
          within the bounds of our Service.
        </p>
        <p>
          <strong>Third-Party Websites/Applications.</strong>The Service may
          contain links to other websites/applications (such as Google Drive or
          Dropbox) and other websites/applications may reference or link to our
          Service. These third-party services are not controlled by us. We
          encourage our users to read the privacy policies of each website and
          application with which they interact. We do not endorse, screen, or
          approve, and are not responsible for, the privacy practices or content
          of such other websites or applications. Visiting these other websites
          or applications is at your own risk.
        </p>
        <p>
          <strong>Children’s Privacy.</strong> The Services are not directed to
          children under 13, and we do not knowingly collect personal
          information from children. If you learn that your child has provided
          us with personal information without your consent, you may contact us
          as set forth below. If we learn that we have collected a child’s
          personal information in violation of applicable law, we will promptly
          take steps to delete such information and terminate the child’s
          account.
        </p>
        <p>
          <strong>Supervisory Authority.</strong> . If you are located in the
          European Economic Area or the UK, you have the right to lodge a
          complaint with a supervisory authority if you believe our processing
          of your personal information violates applicable law.
        </p>
        <p>
          <strong>Changes to Our Privacy Policy.</strong> We may revise this
          Privacy Policy from time to time at our sole discretion. If there are
          any material changes to this Privacy Policy, we will notify you as
          required by applicable law. You understand and agree that you will be
          deemed to have accepted the updated Privacy Policy if you continue to
          use the Service after the new Privacy Policy takes effect.
        </p>
      </section>
      <section className="rich-text-section" id="contact-us">
        <h2 className="title-s mt-8"> 10. Contact Us</h2>
        <p>
          If you have any questions or concerns regarding our privacy practices
          or this Privacy Policy, please contact us via email to hello@stroke.so
        </p>
        <p>
          Happy Vibes, Inc.<br></br>1606 Headway Cir STE 9794<br></br> Austin,
          Texas 78754, United States
        </p>
      </section>
    </div>
  );
};

export default Content;
